# -*- coding: utf-8 -*-
"""Arbitrary value imoutation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzAIgO4_ZNVCfLJPN-Xy5HcxsU4ZOhxD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

df = pd.read_csv('titanic_toy.csv')

df.head()

df.isnull().sum()

X= df.drop(columns=['Survived'])
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

X_train['Age_99'] = X_train['Age'].fillna(99)
X_train['Age_minus1'] = X_train['Age'].fillna(-1)

X_train['Fare_999'] = X_train['Fare'].fillna(999)
X_train['Fare_minus1'] = X_train['Fare'].fillna(-1)

X_train.sample(5)

print('Original Age variable variance:', X_train['Age'].var())
print('Age imputed with median variance:', X_train['Age_99'].var())
print('Age imputed with mean variance:', X_train['Age_minus1'].var())

print('Original Fare variable variance:', X_train['Fare'].var())
print('Fare imputed with median variance:', X_train['Fare_999'].var())
print('Fare imputed with mean variance:', X_train['Fare_minus1'].var())

fig = plt.figure()
ax = fig.add_subplot(111)

# Original variable distrubution
X_train['Age'].plot(kind='kde',ax=ax)

#variable imputed with the median
X_train['Age_99'].plot(kind='kde',ax=ax,color='red')

#Variable imputed with the mean
X_train['Age_minus1'].plot(kind='kde',ax=ax,color='green')

lines,labels = ax.get_legend_handles_labels()
ax.legend(lines,labels,loc='best')

fig = plt.figure()
ax = fig.add_subplot(111)

# Original variable distrubution
X_train['Fare'].plot(kind='kde',ax=ax)

#variable imputed with the median
X_train['Fare_999'].plot(kind='kde',ax=ax,color='red')

#Variable imputed with the mean
X_train['Fare_minus1'].plot(kind='kde',ax=ax,color='green')

lines,labels = ax.get_legend_handles_labels()
ax.legend(lines,labels,loc='best')

X_train.cov()

X_train.corr()

"""# **Using sklearn**"""

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

imputer1 = SimpleImputer(strategy='constant',fill_value=99)
imputer2 = SimpleImputer(strategy='constant',fill_value=999)

trf = ColumnTransformer([
    ('imputer1',imputer1,['Age']),
    ('imputer2',imputer2,['Fare'])
],remainder='passthrough')

trf.fit(X_train)

trf.named_transformers_['imputer1'].statistics_



trf.named_transformers_['imputer2'].statistics_

X_train = trf.transform(X_train)
X_test = trf.transform(X_test)

X_train

